### ISSUE TITLE
High Performances prediction

### ISSUE THREAD

**Issue by datapink** [datapink/robosat.pink#10]
Explore if alternate prediction methods can significantly increase speed performances.

At this stage, identified leads are:
 -  ONNX with Caffe2 or ONNXRuntime
 -  PyTorch JIT
 - Smaller models (by design or after pruning)

TODO:

- [x] ONNX export
- [x] JIT export
- [ ] Give a look at Glow
- [ ] JIT C++ predict
- [ ] JIT C++ packaging
- [ ] SqueezeNet bench

**Comment by dselivanov** [comment]
We are very happy with ONNX and ONNXRuntime for inference. Moreover ONNXRuntime now supports different accelerators like TensorRT, ngraph, etc. My strong feel is that ONNX + ONNXRuntime cover majority of workloads.

Also  in production we use https://github.com/NVIDIA/tensorrt-inference-server which gives you many extra features such as load balancing, queue, automatic batching and many more.
