### ISSUE TITLE
CUDA issue with RTX cards

### ISSUE THREAD

**Issue by datapink** [datapink/robosat.pink#3]
Looks like CUDA version, able to fully support RTX cards, 
is not yet packaged in the latest official PyTorch release (at least till 1.0.1).

Cf: https://github.com/pytorch/pytorch/issues/15797

With RoboSat.pink leads to crash tools using CUDA as ```rsp train```

A workaround is to switch to PyTorch nightly build:

So after RoboSat.pink whole install:
```
python3 -m pip uninstall torch torchvision
python3 -m pip install torchvision_nightly
python3 -m pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
```

**Comment by ocourtin** [comment]
To be more accurate, RTX need Cuda 10.
And 1.0.1 release is enough, (no need to take the nightly)
but have to be installed  with a Wheel, and not from PyPi.

```pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl```

**Comment by ShijianXu** [comment]
Hi, still have a problem.

I used the solution you provided and when run: `torch.version.cuda`, it will show `10.0.130`. However, if I continue to install torchvision via `pip3 install torchvision`, it will show this:

> Collecting torchvision
https://files.pythonhosted.org/packages/fb/01/03fd7e503c16b3dc262483e5555ad40974ab5da8b9879e164b56c1f4ef6f/torchvision-0.2.2.post3-py2.py3-none-any.whl
Collecting six (from torchvision)
https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting numpy (from torchvision)
https://files.pythonhosted.org/packages/c1/e2/4db8df8f6cddc98e7d7c537245ef2f4e41a1ed17bf0c3177ab3cc6beac7f/numpy-1.16.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting pillow>=4.1.1 (from torchvision)
https://files.pythonhosted.org/packages/d2/c2/f84b1e57416755e967236468dcfb0fad7fd911f707185efc4ba8834a1a94/Pillow-6.0.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting torch (from torchvision)
https://files.pythonhosted.org/packages/31/ca/dd2c64f8ab5e7985c4af6e62da933849293906edcdb70dac679c93477733/torch-1.0.1.post2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: six, numpy, pillow, torch, torchvision
Successfully installed numpy-1.16.3 pillow-6.0.0 six-1.12.0 torch-1.0.1.post2 torchvision-0.2.2.post3

Apparently, it install a `torch` again. And when I run `torch.version.cuda` again, it will return to `9.0.176`. As a result, the error `THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument` still exists. This is frustrated.

Do you know how to solve it?

**Comment by ocourtin** [comment]
Just don't install torchvision again. ^^

```pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl```

Is enough.
