### ISSUE TITLE
GeoJson input must be provided in EPSG:4326

### ISSUE THREAD

**Issue by datapink** [datapink/robosat.pink#4]
With ```rsp rasterize``` tool, if GeoJSON is provided input, 
not check is performed to look about CRS, and if needed perform reprojection.

**Comment by Imanflow** [comment]
Hey! New here, I discovered the project in FOSDEM. This looks like a task I could handle.

**Comment by ocourtin** [comment]
@Imanflow 

Be my guest !  :)

PR is always welcome !

I guess the most tricky part on this one will be to take in consideration all valid ways to express the very same CRS :

  - EPSG:4326
  - urn:ogc:def:crs:OGC::CRS84
  - urn:ogc:def:crs:OGC:1.3:CRS84
  - urn:EPSG:geographicCRS:4326
  - urn:ogc:def:crs:EPSG:4326
  - urn:ogc:def:crs:EPSG::4326
  - urn:ogc:def:crs:EPSG:6.6:4326
  - urn:x-ogc:def:crs:EPSG:6.6:4326
  - http://www.opengis.net/gml/srs/epsg.xml#4326
  - http://www.epsg.org/6.11.2/4326



And as there's still no dev documentation of any kind don't hesitate to ask any questions !
(the ```Makefile``` is supposed to be dev friendly ^^)

**Comment by Imanflow** [comment]
Is including an extra library an option? [Fiona](https://github.com/Toblerity/Fiona) can open and handle all the different ways of defining a CRS and we can retrieve it as easy as `.crs`

**Comment by ocourtin** [comment]
Doing this would mean:
 - A new dependancy to maintain 
 - Parsing the GeoJSON input file twice

Not really convinced at this stage...


What about taking the last part of CRS and then applying conversion if needed (e.g CRS84 -> 4326)
The shadow part is to be (quite) sure that there's only few special conversions to deal with...

**Comment by Imanflow** [comment]
Answering to your points:

- Fiona is a quite standard python library for shapefiles/GeoJSON files, not likely to change something as basic as `.open` or be left unmantained. 
- There is no need to parse it twice. If opened with `fiona` on first place
(lines 174, 175 become `with fiona.open(geojson_file) as feature_collection:`), 
the code keeps the same syntax.

I really think it makes more sense than reinvent the wheel and try to catch manually all possible options.

**Comment by Imanflow** [comment]
I created the PR #17 so you can see how it would look like and decide.

**Comment by ocourtin** [comment]
Gave a look on fiona on these issue. And still not convinced :)

As for instance with fiona EPSG:900913 CRS, 
even if not defined on gdal espg file is not automagically converted to related EPSG:3857

Actual json parser is a SAX kind, so allow to deal with big files, maybe bigger than RAM available.
Fiona approach have to load the whole file before.
A quick bench to compare file opening: 1600 ms vs 27 ms on a same file.

**Comment by ocourtin** [comment]
@Imanflow 

Maybe an another approach could be to look on rasterio.CRS side,
with ```from_string()```  and ```to_epsg()```

As it's already imported and supposed to work on the CRS string only...

**Comment by Imanflow** [comment]
It can only read EPSG codes or WKT, `from_string()` asks for `'EPSG:4326'`so it would be possible to extract the EPSG code directly from the string, but we would need to manually convert to EPSG this ones:

- urn:ogc:def:crs:OGC::CRS84
- urn:ogc:def:crs:OGC:1.3:CRS84

**Comment by ocourtin** [comment]
So in this case, what about something like that ?

```
crs_mapping = { 'CRS84':'4326', '900913':'3857' }    
srid = crs.split(':')[-1]
srid = srid if srid not in crs_mapping else crs_mapping[srid]
```
