### ISSUE TITLE
Pillow-simd install not possible anymore since PyPI

### ISSUE THREAD

**Issue by datapink** [datapink/robosat.pink#5]
Since PyPI RoboSat.ping packaging, 
we have to choose at the install time (performed by ```setup.py```) if we want ```Pillow or Pillow-simd```.
and not really designed to switch it back thereafter...

But as torchvision use ```env python``` in it's shebang, cf https://github.com/pytorch/vision/pull/773
it leads with RoboSat.pink to install ```Pillow``` even if we wanted ```Pillow-simd```.

Have to find a workaround, as performances with ```rsp download``` and ```rsp compare``` are significantly impacted.

Nota: don't impact ```rsp train``` performances as it's relly on OpenCV.

**Comment by datapink** [comment]
A workaround lead would be to fully remove PIL and keep OpenCV only for image manipulations.

But would imply to deal with PNG Palette feature (not implemented with OpenCV).

**Comment by ocourtin** [comment]
Since compare is multithreaded with #27, performances regressions are no more an issue.
And we want to keep install as easier as `pip3 install RoboSat.pink`, so pillow-simd is no more a target.
