### ISSUE TITLE
 Problem with documentation

### ISSUE THREAD

**Issue by ssalvadeo** [datapink/robosat.pink#62]
When I try to execute the command.

**rsp rasterize --type Building --geojson ds/lyon_roofprint.json --cover ds/cover ds/labels**

I get the following error:

**CONFIG ERROR: Either ~ / .rsp_config or RSP_CONFIG env var or --config parameter, is required.**

**Comment by sulabh9999** [comment]
```
$ rsp rasterize --geojson ds/tiles.json --type Building --cover ds/images/cover.csv --out ds/labels

ERROR: Either ~/.rsp_config or RSP_CONFIG env var or --config parameter, is required.
```
Same here also..please help me.
