### ISSUE TITLE
rsp cover does not handle negative coordinates

### ISSUE THREAD

**Issue by paumillet** [datapink/robosat.pink#64]
Hello,

Thanks for sharing your work. 
I've just starting playing with Robosat.pink and my area of interest is located in Nantes, France surroundings. For this area, longitudes are negative and are then not recognized as argument for parameter `--bbox`. I actually got the error `rsp cover: error: argument --bbox: expected one argument` so I guess they are detected as being the next parameter because of the sign `-`.

I personally fixed it with a simple trick, I now enter my bounding box with squared brackets `[]` and then process the input string to remove the brackets in `cover.py`.  
But it's probably not the only place where negative longitudes could have an impact in Robosat.pink. I then let you handle this issue to have a proper update on the whole repository but I stay available if you need.

Cheers,
Pauline

**Comment by ocourtin** [comment]
Hi @paumillet 

Thanks for this report, i've just commited a fix on this, 
thanks in advance to test it and check it...

Cheers,

**Comment by paumillet** [comment]
Hi @ocourtin ,
I'm afraid your commit did not fix the issue, I still have the same error...

**Comment by paumillet** [comment]
My bad, I was in the wrong virtual env, I works !

**Comment by ocourtin** [comment]
Great ! 
And thanks for the check Pauline.
