### ISSUE TITLE
Cover and rasterized of LineString and Point

### ISSUE THREAD

**Issue by cthnguyen** [datapink/robosat.pink#65]
Hello ! 

I'm trying to rasterized polygons with robosatpink, but with different channels (background, fill, vertex, edge) that I'm going to stack afterward. I manage to have the background and the fill by just rasterizing the polygons. First, I'm using `rsp cover` and it gives me this error when I'm trying to use a geojson with LineString or Point objects : 

```
ERROR: invalid or unsupported GeoJSON.
```

The errors seems to come from this part of the code in the cover function : 

```
for feature in tqdm(features["features"], ascii=True, unit="feature"):
        tiles.extend(map(tuple, burntiles.burn([feature], args.zoom).tolist()))
```

This is an extract of my geojson : 

```
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 0 }, "geometry": { "type": "LineString", "coordinates": [ [ 2.546836020138071, 48.235503411046125 ], [ 2.546867700160758, 48.235421652155814 ], [ 2.546878714235626, 48.235393801074224 ], [ 2.546772501775777, 48.235371799023063 ], [ 2.546792278759802, 48.235421362983146 ], [ 2.546762053662689, 48.235490530456403 ], [ 2.546836020138071, 48.235503411046125 ] ] } },

```

I noticed that compared to a geojson with Polygon which works fine with robotsat pink is that in the geojson with Polygon, there is an extra bracket for coordinates. Adding it to the geojson is not working. 

Any insights to this problem ? Or another way so that I can get multi-layers images of rasterized polygons with Slippy map format ? 

Thanks a lot !

**Comment by ocourtin** [comment]
Hi @cthnguyen !

Two reactions, at this stage:

- Could you try again with latest RoboSat.pink master branch version (to be sure it's not already been fixed) ?
  And if it's still an issue, could you provide few more instructions in order to reproduce it ?

- Are you aware that you can use PostGIS or SpatiaLite to express a SQL query with rsp rasterize ?
  (could be helpful to extract more easily such specific features)

**Comment by cthnguyen** [comment]
Thanks a lot for the ideas ! I didn't think of using PostGis to get the features, and once it is transform to a polygon, it works well ! 

Thank you !
