### ISSUE TITLE
How to rsp tile only where I actually have labels?

### ISSUE THREAD

**Issue by baristahell** [datapink/robosat.pink#67]
Hi RSP!

I'm trying to extract images in the tile format from a VRT, so nothing too fancy... Except I have imagery for large zones that aren't covered by my labels and a naïve `rsp tile ...` extracts the images for non-covered zones too and it's a bit too much for mu computer. 

I'd like to know if there was a way to constrain the tiling in order to only get images of labeled zones. I already generated my cover CSV file using `rsp cover` on my GeoJSON but I don't really know if it's usable for this purpose. But maybe I'm missing something since it's a feature for `rsp download`.

Thanks!

**Comment by ocourtin** [comment]
Hi @baristahell 

Indeed, `rsp tile` didn't provide `--cover` filtering.  
As it was missing, I just add it.
Thanks in advance to test it, and to report any issue...

**Comment by baristahell** [comment]
Fantastic, thanks a lot, I'll make sure and report any issue!
