### ISSUE TITLE
Rsp cover doesn't work with multipolygon object 

### ISSUE THREAD

**Issue by cthnguyen** [datapink/robosat.pink#68]
Hello ! 
I'm trying to use the command `rsp cover`with a geojson with multipolygon objects but it doesn't work, it returns the following error : `ERROR: invalid or unsupported GeoJSON.`
Is polygon the only object supported by rsp ? 
Thanks !

**Comment by ocourtin** [comment]
Hi @cthnguyen, thanks for this report (was also related to #29)

Previous commit should fix it.
Thanks in advance to test it on your side, and to report any new issue.
