### ISSUE TITLE
error with rsp train

### ISSUE THREAD

**Issue by paumillet** [datapink/robosat.pink#69]
Hello,

I've troubles using the train command `rsp train`.
The full command I launched:
```bash
rsp train --config ds/config.toml --epochs 10 ds ds/model
```
and I got the following error message:
```bash
num_samples should be a positive integer value, but got num_samples=0
```

I created my dataset by following those 4 steps:
1. Extract data from an osm .pbf with `rsp extract`,
2. then I rasterized it with:  
```bash
rsp rasterize --config ds/config.toml --type Building --geojson groundtruth.geojson --cover ds/cover ds/labels
```
3. create tiles from my imagery:  
```bash
rsp tile --cover ds/cover --zoom 14 ds/data/image.jp2 ds/tiles
```
4. finally create the training dataset:  
```bash
rsp cover --cover ds/cover --splits 70/30 ds/training/cover ds/validation/cover
rsp subset --dir ds/tiles --cover ds/training/cover ds/training/images
rsp subset --dir ds/labels --cover ds/training/cover ds/training/labels
rsp subset --dir ds/tiles --cover ds/validation/cover ds/validation/images
rsp subset --dir ds/labels --cover ds/validation/cover ds/validation/labels
```

Any advice to get around this error?
Thanks

**Comment by ocourtin** [comment]
Hi @paumillet 

At first sight the commands you lauched looks good.
And this error message is related to inconsistent DataSet (for instance a tile present in images but not in labels)

So:
- Did you use the latest RoboSat.pink version (0.5.1 or master) ?
- Could you check that ds/training/images and ds/training/labels are consistents ?
  (and same for validation)


HTH,

**Comment by paumillet** [comment]
Hi @ocourtin,

I'm indeed working with version 0.5.1 and I checked consistency between labels and images, evrything was fine.

I actually realized that it works when I turned all folders named "tiles" to "images".
