### ISSUE TITLE
Possible to append new training  to the trained epochs pth ?

### ISSUE THREAD

**Issue by wucangeo** [datapink/robosat.pink#70]
I'm new to this.
Maybe it's not a problem.

RoboSat.Pink is a great tool, and saved months of my time. 
Thanks!
I have trained about 10k building polygon in one area, and it works great.
Is it Possible to append new training  to the trained epochs pth? Instead of training from the very beginning.
If it could be, that will improve extraction accuracy, and  save a lot of time.
Hope you could reply, Thanks!

**Comment by ocourtin** [comment]
Hi @wucangeo 
Thanks for your feedback and enthusiasm !

And yes this is a basic feature, already available...
`rsp train -h` will give show you all available options.

What you're looking for is something like:
`rsp train --resume --checkpoint PATH_TO_YOUR_PTH --epochs TOTAL_NB_EPOCHS ... `


HTH,

**Comment by wucangeo** [comment]
@ocourtin 
Wow, It looks great. I'm gonna try these on.
That's very ice of you.
thanks！
