### ISSUE TITLE
How do i get Road vector json with wfs for lyon?

### ISSUE THREAD

**Issue by saiakhil19932** [datapink/robosat.pink#74]
Hi
I am following this doc_opendata_to_opendataset.md, my question is, I need to train a model for road segmentation, how can i collect road labels for this imagery \

rsp download --type WMS 'https://download.data.grandlyon.com/wms/grandlyon?SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&LAYERS=Ortho2015_vue_ensemble_16cm_CC46&WIDTH=512&HEIGHT=512&CRS=EPSG:3857&BBOX={xmin},{ymin},{xmax},{ymax}&FORMAT=image/jpeg' --rate 20 ds/cover ds/images  

I tried many resources i could not find any vector prints for road. Please help.

**Comment by ocourtin** [comment]
This is not an issue about RoboSat.pink itself.

For information, for such kind of assistance,
DataPink provide commercial support, and training courses on GeoSpatial Computer Vision.
Feel free to ask for a quotation: hello@datapink.com
