### ISSUE TITLE
Add MultiClass support 

### ISSUE THREAD

**Issue by datapink** [datapink/robosat.pink#8]
MultiClass (as N binary outputs)
- [ ] Train / model / losses / metrics / config file
- [ ] Rasterize
- [ ] Predict
- [ ] Compare
- [ ] Auto-Weighted QoD Metrics ?

**Comment by ocourtin** [comment]
A first move on this one will be to not be obliged to define background class.
Either in config file, or in label images

**Comment by ketograph** [comment]
I'm currently working on implementing multi-class segmentation (one network predicts multiple different classes), is there a way to merge these two approaches? Or should I just work on my own and merge it latter?

**Comment by ocourtin** [comment]
Hi @ketograph,

Few reactions points:

- Great to hear you're working on enhancing RoboSat.pink code

- Best way to bring code/features is to send Pull Request

- If you got any questions on implementation you can send message here, 
  or there: https://gitter.im/RoboSatPink
