### ISSUE TITLE
Multi GPU training performance

### ISSUE THREAD

**Issue by dselivanov** [datapink/robosat.pink#82]
From my experience `DistributedDataParallel`  scales much better  than `DataParallel`. As of now I've tried to train on 1 to 8 Tesla V100 and training doesn't scale after 4 GPU. And during the training I see GPU utilisation ~ 50-70%. And when training on a single GPU utilization is close to 100%.
I believe it makes sense for future to use `DistributedDataParallel` instead of `DataParallel`.

**Comment by ocourtin** [comment]
Indeed switching to DP to DDP is clearly a good idea.
Should lead to scale better on multi GPU, but also to allow multi hosts.

PR is welcome on this.
