### ISSUE TITLE
[question] Using multiple images of the same area

### ISSUE THREAD

**Issue by dselivanov** [datapink/robosat.pink#84]
I have multiple images of the same area. As I understand the current structure (Slippy Map) will bot allow to do that... As a workaround I can shift one images relative to each other in order to have non-intersected areas, but this looks like very unattractive hack.

**Comment by ocourtin** [comment]
Hi Dmitryi,

Same images of the same area, refer to time series notion.

And indeed it's not yet supported, but already identified as a wish features, PR or Funding welcome:
https://github.com/datapink/robosat.pink#requests-for-funding

It will mainly imply:
- To deal with xyz path notion to add a time dimension
- Alternate model handling time series (RNN, Attention...)
