### ISSUE TITLE
rsp train - Dataset mask inconsistency

### ISSUE THREAD

**Issue by tgoers** [datapink/robosat.pink#87]
I am running rsp train, this time in an ubuntu environment and am getting the following results (I am following the provided "From Opendata to OpenDataset tutorial"). I realize that I am not using the GPU but I don't have one.

`~/Desktop$ rsp train --config ds/config.toml --epochs 10 --ts 1024,1024 ds ds/model
RoboSat.pink - training on CPU, with 4 workers - (Torch:1.3.1)

==========================================================
WARNING: Are you -really- sure about not training on GPU ?
==========================================================

--- Input tensor from Dataset: ds ---
Channel 1:		 images[band: 1]
Channel 2:		 images[band: 2]
Channel 3:		 images[band: 3]
--- Output Classes ---
Class 0:		 Background
Class 1:		 Building
--- Hyper Parameters ---
nn                       Albunet
loss                     Lovasz
bs                       4
lr                       2.5e-05
ts                       (1024, 1024)
ms                       16
loader                   SemSegTiles
da                       Strong
metrics                  ['iou', 'mcc']
pretrained               True
dap                      1.0
---
Epoch: 1/10 -- UUID: 92b139f4-0eed-11ea-9c08-02e02c55140c
Train:   0%|                                        | 0/2825 [00:00<?, ?batch/s]

ERROR: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/.local/lib/python3.7/site-packages/robosat_pink/loaders/semsegtiles.py", line 75, in __getitem__
    assert tile == self.tiles["labels"][i][0], "Dataset mask inconsistency"
AssertionError: Dataset mask inconsistency
`

**Comment by ocourtin** [comment]
DataSet mask inconsistency means that you're trying to use imagery and labels who don't perfectly match together (because some are lacking, because of wrong resolution....)

As a guess, if you followed the tutorial,
you should not use 1024x1024 tile size tile (but the default 512x512).


And if you don't have a GPU, you should rent one.
It's about 1 euro per hour with OVH Cloud (GTX 1080Ti) .
And it will be about 100 time quicker than with CPU only.

**Comment by oneOfThePeople** [comment]
hi
i have the same problem all my file is 256x256 and match to each other 
you have any idea what can be the problem?
