### ISSUE TITLE
Error in RoboSat.pink 101 

### ISSUE THREAD

**Issue by SBCV** [datapink/robosat.pink#89]
The error occurs in [Retrieve and tile labels](https://github.com/datapink/robosat.pink/blob/master/docs/101.md#retrieve-and-tile-labels) 

Running the following bash script

```
# Filter initial GeoJSON to keep only meaningful features
for geojson in `ls ds/grid_*.geojson`
do
        ogr2ogr -f SQLite ds/tanzania_labels.sqlite $geojson -dsco SPATIALITE=YES -t_srs EPSG:3857 -nlt PROMOTE_TO_MULTI -nln building -lco GEOMETRY_NAME=geom -append 2> /dev/null
done

ogr2ogr -f GeoJSON ds/tanzania_labels.json ds/tanzania_labels.sqlite -dialect sqlite -sql "SELECT Buffer(geom, -0.25) AS geom FROM building WHERE condition = 'Complete' OR condition = 'Incomplete'"

# Generate Labels
rsp rasterize --geojson ds/tanzania_labels.json --type Building --config tanzania.toml --cover ds/images/cover.csv ds/labels
```

produces the following error message:
`ERROR: [Errno 2] No such file or directory: 'ds/tanzania_labels.json'`

Side note: the generated `tanzania_labels.sqlite` file is empty. Therefore, I assume that the error lies in 
```
for geojson in `ls ds/grid_*.geojson`
do
        ogr2ogr -f SQLite ds/tanzania_labels.sqlite $geojson -dsco SPATIALITE=YES -t_srs EPSG:3857 -nlt PROMOTE_TO_MULTI -nln building -lco GEOMETRY_NAME=geom -append 2> /dev/null
done
```

Any ideas?
 
Bests,
Sebastian

**Comment by ocourtin** [comment]
Hi Sebastian,

I cannot reproduce the error, on my own (with latest RoboSat.pink 0.5.5 version)

At this stage, i assume your copy/paste on previous step missed the latest line,
and ```mv  grid_*.geojson ds``` never been performed...

Could you give a check ?

**Comment by SBCV** [comment]
I think I did, since my `ds` folder contains the following files
```
grid_001.geojson
grid_001.tif
grid_022.geojson
grid_022.tif
grid_023.geojson
grid_023.tif
grid_028.geojson
grid_028.tif
grid_029.geojson
grid_029.tif
grid_035.geojson
grid_035.tif
grid_036.geojson
grid_036.tif
grid_042.geojson
grid_042.tif
grid_043.geojson
grid_043.tif
grid_049.geojson
grid_049.tif
grid_050.geojson
grid_050.tif
grid_051.geojson
grid_051.tif
grid_058.geojson
grid_058.tif
images
labels
tanzania_labels.sqlite
tanzania_labels.sqlite-journal
```

**Comment by SBCV** [comment]
Do you mean with `latest` the version that is installed with `pip3 install RoboSat.pink`?
Btw: Does the repository contain a python script that allows to run the complete 101 example?

**Comment by ocourtin** [comment]
Indeed, it's look fine.

```rsp info --version```   give you the version installed

Could you also give a:
```ogrinfo --info```


And if you to launch all the 101 tuto:
```
wget  https://raw.githubusercontent.com/datapink/robosat.pink/master/docs/101.md
mkdir 101 && sed -n -e '/```bash/,/```/ p' 101.md | sed -e '/```/d' > 101/.101 && cd 101 && sh .101
```

**Comment by SBCV** [comment]
`rsp info --version` gives me `0.5.5` 
and
`ogrinfo --info` gives me
```
 ogrinfo --info
Usage: ogrinfo [--help-general] [-ro] [-q] [-where restricted_where|@filename]
               [-spat xmin ymin xmax ymax] [-geomfield field] [-fid fid]
               [-sql statement|@filename] [-dialect sql_dialect] [-al] [-rl] [-so] [-fields={YES/NO}]
               [-geom={YES/NO/SUMMARY}] [-formats] [[-oo NAME=VALUE] ...]
               [-nomd] [-listmdd] [-mdd domain|`all`]*
               [-nocount] [-noextent]
               datasource_name [layer [layer ...]]

FAILURE: Unknown option name '--info'
```

**Comment by SBCV** [comment]
Btw: `ogrinfo --version` gives me `GDAL 2.2.3, released 2017/11/20`

**Comment by ocourtin** [comment]
That's it.  Your GDAL version is too old.
Should be at least 2.3.1 (cf  https://gdal.org/drivers/vector/sqlite.html#using-the-spatialite-library-spatial-extension-for-sqlite)

(and for the record tested with 2.4.0)

Best,

**Comment by SBCV** [comment]
Thank you for the fast response!
