### ISSUE TITLE
rsp tile 

### ISSUE THREAD

**Issue by jaigsingla** [datapink/robosat.pink#90]
Hi,

i have tried to use rsp tile with different zoom levels 2-5,21 with tilesize of 256,256 in jpg format 
but it does not generate any tile. it say 0tile.  input image size is small 777x674 and resoultion  is around 1.2 meters. 

what should be parameters for different resolution and sizes of images.

**Comment by ocourtin** [comment]
Hi @jaigsingla 

`rsp tile` expect georeferenced imagery, to be able to compute extent, and so to tile it.
Could you perform a ` gdalinfo YOUR_INPUT_IMAGE_PATH | grep Coordinate` to check it...

**Comment by ocourtin** [comment]
But not sure to fully understand your initial question.

Below a minimal working example:
```
wget "https://download.data.grandlyon.com/files/grandlyon/imagerie/ortho2018/ortho/GeoTiff_YcBcR/1km_8cm_CC46/1841_5174_08_CC46.tif"
wget "https://download.data.grandlyon.com/files/grandlyon/imagerie/ortho2018/ortho/GeoTiff_YcBcR/1km_8cm_CC46/1842_5174_08_CC46.tif"
rsp tile --zoom 16 *.tif tiles
rsp tile --zoom 18 *tif tiles

```

**Comment by jaigsingla** [comment]
HI, its working. there was some problem with input file.
