### ISSUE TITLE
Name Conflict of geojson.py and geojson library

### ISSUE THREAD

**Issue by SBCV** [datapink/robosat.pink#91]
Running  
```
import sys
from robosat_pink.tools.__main__ import main

arguments = ['rsp', 'extract', 
             '--type', 'Building',
             'some_file.pbf',
             'some_file.json']
sys.argv = arguments
sys.exit(main())
```
from within the `robosat_pink` module causes the following error message: `ERROR: module 'geojson' has no attribute 'Polygon'`

Currently, this repository contains the file `robosat.pink/robosat_pink/geojson.py`. This file name conflicts with the following package [https://pypi.org/project/geojson](https://pypi.org/project/geojson), if the `robosat_pink` folder is added to the python path before the `geojson` library.

Would it be possible to rename this file in order to remove this conflict?

**Comment by ocourtin** [comment]
Hi @SBCV, thanks for this report.

At this point, i'm not sure to fully understand your issue, nor to reproduce it.

As `robosat.pink` dir should indeed be in `PYTHONPATH`,  
and so: `robosat_pink.geojson` != `geojson`

**Comment by SBCV** [comment]
My bad. I executed the above script from the top level folder of `robosat.pink` (which contains the `geojson.py` file). Therefore, python picked up the `geojson.py` file before the library with the same name. I think you could just close this issue - on the other hand it might be useful to rename this file anyways.

**Comment by SBCV** [comment]
And thank you for the fast response!
