### ISSUE TITLE
"rsp info" broken in version 0.6.1 (still works in 0.5.5)

### ISSUE THREAD

**Issue by ChrisJoubert2501** [datapink/robosat.pink#92]
I installed robosat.pink with pip (version 0.6.1).
But when I run "rsp info" it gives the following:

ERROR: not enough values to unpack (expected 2, got 1)

"rsp info --version" still works.
I'm running in an anaconda environment with Python 3.7.6.

When installing robosat.pink version 0.5.5, "rsp info" still works as expected.

**Comment by ocourtin** [comment]
@ChrisJoubert2501 

Thanks for the report, could you launch:
`export RSP_DEBUG=1 && rsp info`

And send the whole stacktrace...

**Comment by ChrisJoubert2501** [comment]
Traceback (most recent call last):
  File "/home/cjoubert/miniconda3/envs/rsp_env5/bin/rsp", line 8, in <module>
    sys.exit(main())
  File "/home/cjoubert/miniconda3/envs/rsp_env5/lib/python3.7/site-packages/robosat_pink/tools/__main__.py", line 43, in main
    args.func(args)
  File "/home/cjoubert/miniconda3/envs/rsp_env5/lib/python3.7/site-packages/robosat_pink/tools/info.py", line 70, in main
    k, v = line.strip().split("=")
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by ocourtin** [comment]
Thanks
Related to new Linux distribution release info.
For information, what is the content of your `/etc/os-release` file ?

I will add a try/catch

**Comment by ChrisJoubert2501** [comment]
/etc/os-release content:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by ocourtin** [comment]
Thanks, 
Related to the empty line i guess.
b53764f sould do

`pip3 install git+https://github.com/datapink/robosat.pink` to test it from master

**Comment by ocourtin** [comment]
@ChrisJoubert2501 
FYI just released a 0.6.2
