### ISSUE TITLE
rsp train issue: Function MulBackward0 returned an invalid gradient at index 0

### ISSUE THREAD

**Issue by ChrisJoubert2501** [datapink/robosat.pink#93]
Notice
---
First, I'm not sure if this is the right place to post this, so please advise / close issue if necessary.

Issue
---
**I am running rsp train:**

rsp train --config cape_town.toml --epochs 5 --train_dataset ds/train --eval_dataset ds/eval --workers 1 --bs 1 --out ds/pth

**...and running into the following error:**

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/cjoubert/miniconda3/envs/rsp_env5/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/cjoubert/miniconda3/envs/rsp_env5/lib/python3.7/site-packages/robosat_pink/tools/train.py", line 228, in gpu_worker
    rank, train_loader, config, args.classes_weights, log, csv_train, nn, criterion, "train", epoch, optimizer
  File "/home/cjoubert/miniconda3/envs/rsp_env5/lib/python3.7/site-packages/robosat_pink/tools/train.py", line 327, in do_epoch
    _do_epoch()
  File "/home/cjoubert/miniconda3/envs/rsp_env5/lib/python3.7/site-packages/robosat_pink/tools/train.py", line 293, in _do_epoch
    loss.backward()
  File "/home/cjoubert/miniconda3/envs/rsp_env5/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/cjoubert/miniconda3/envs/rsp_env5/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function MulBackward0 returned an invalid gradient at index 0 - expected type torch.cuda.FloatTensor but got torch.cuda.DoubleTensor

Data: 
---
tiff files of Cape Town, prepared exactly as in the tutorial (ts = 1024, 1024).

Setup: 
---
I am running in Anaconda environment, Python 3.7.6.
4 GPUs.
Due to considerations for other users, I cannot update the CUDA drivers on our computer cluster yet.
So I can only use CUDA 10.0 (not 10.1).
This forces me to install Robosat.pink using pip (latest version), then downgrade torch to 1.2.0, torchvision to 0.4.0, and PIL to 6.2.1. Otherwise torch doesn't pick up the GPUs (torch.cuda.is_available(): False).
I don't know if this is related to my problem.
I know a bit about deep learning, but I haven't used torch before.

**Comment by ocourtin** [comment]
@ChrisJoubert2501 
By CUDA Drivers you mean CUDA or you mean NVIDIA Drivers ?
As PyTorch embed, his own CUDA/CUDNN libs, when installed with `pip3`

And indeed RoboSat.pink 0.6.x expects at the very least PyTorch 1.3.x (for DDP support)
So not that surprising it ends in error.

Suggestions:
 - Isolate your environment (for instance with virtualenv or Docker) to install latest RoboSat.pink
 - Install RoboSat.pink 0.5.x  (but it will use poorly your 4 GPUs, without DDP)
 
HTH,

**Comment by ocourtin** [comment]
I close it, feel free to re-open if still an issue with latest RoboSat.pink 
and with official dependencies libs versions.

**Comment by ChrisJoubert2501** [comment]
Hi Mr Courtin,

Thank you for the help. In the end I tried many different ways to get it to work with the older Nvidia driver, without success.
I negotiated that we update the Nvidia drivers to the latest version, and now everything works.
I have my first prediction already. Will post some results later.

Thank you again.

**Comment by ocourtin** [comment]
Thanks for the feedback,
And Nvidia drivers was indeed the best option...

One more thing, related to your previous example, `--bs 1` could seems peculiar, 
as you loose batch normalization. `--bs 4` or `--bs 8` worth also to be tried, to compare accuracy...

Best,

**Comment by ChrisJoubert2501** [comment]
Thanks for the tip.
So far, I can only run with `--bs 2`. 
`--bs 4` gives me the out of memory error:
*RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 2; 15.90 GiB total capacity; 14.14 GiB already allocated; 385.38 MiB free; 14.81 GiB reserved in total by PyTorch)*

In my input imagery (ds), I have about 1600 tiles with 1024x1024 tiles size.
Each .webp ranges from 600kB to 1000kB.
Should I stick to smaller tile sizes?

**Comment by ChrisJoubert2501** [comment]
![CapeTown_Building_Footprints_Prediction](https://user-images.githubusercontent.com/12845965/73013412-91887d80-3e18-11ea-97c4-105b9c1a3af5.jpeg)
After 30 epochs, results don't look too bad :) (`--bs 1`)

**Comment by ocourtin** [comment]
@ChrisJoubert2501 
Indeed increasing `ts`, imply more VRAM available to handle it
(so to reduce `bs` if not enough available)

PR or funding to implement Apex (aka mixed precision training) would be welcome...
