### ISSUE TITLE
error: loss

### ISSUE THREAD

**Issue by jaigsingla** [datapink/robosat.pink#94]
Hi ocourtin,

I used your latest developed library along with GPU support . I prepared my dataset as  per https://github.com/datapink/robosat.pink/blob/v0.5.5/docs/101.md#retrieve-and-tile-labels , this example. 

but, while running rsp train , getting error: 'loss'

**Comment by ocourtin** [comment]
@jaigsingla 

Several reactions:

- RoboSat.pink latest stable version is 0.6.2, thanks to upgrade: `pip3 install RoboSat.pink == 0.6.2`

- Related latest 101 is: https://github.com/datapink/robosat.pink/blob/master/docs/101.md

- Config file have been improved between 0.5.x and 0.6.x, so pay attention on: 
  https://github.com/datapink/robosat.pink/blob/master/docs/101.md#configuration-file

For instance `loss` is now in `train` section and no more in `model` one.


HTH,
