### ISSUE TITLE
resnet50 path offline

### ISSUE THREAD

**Issue by jaigsingla** [datapink/robosat.pink#95]
I have downloaded resnet50.pth on my machine. now tried with --checkpoint path to resnet50 but, does not work. it is still searching this  on URL . pls suggest how to link it offline

**Comment by ocourtin** [comment]
There's no need to do such a thing.
As encoder .pth is automagically download once if missing.

And `rsp train --checkpoint` refer to a checkpoint from your whole model (`Albunet` by default)

**Comment by jaigsingla** [comment]
Actually, m not connected to internet and it wants internet to fetch resnet50 which I have downloded locally. So, want to specify local path of resnet50 model

**Comment by ocourtin** [comment]
This feature is not implemented right now.

So 3 ways to work it out:
- Hack it. By reversing the local resnet .pth path
- or code yourself the feature, and send a Pull Request
- or fund the feature, to allow me, or someone, else to write it.

**Comment by jaigsingla** [comment]
this is closed. thanks
