### ISSUE TITLE
unable to load augmentation module error

### ISSUE THREAD

**Issue by jaigsingla** [datapink/robosat.pink#98]
Train 0%|
unable to load data augmentation module.

**Comment by ocourtin** [comment]
DataPink provide training session and assistance, on GeoSpatial Computer Vision,
feel free to ask for a quotation.

**Comment by jaigsingla** [comment]
Ocurtin,  I want to try this library and want to make use of this but cannot proceed without your help. I know these are trivial questions to you and you are looking for funds also. But, it's not that easy at our end. Moreover, we don't even know how it will perform on our data. Once it performs well and for future upgrades we have justification to buy your products too. 
Please help to check the output it generates.

**Comment by ocourtin** [comment]
I don't like the way you behave.
And will not help you for free.
Period.
